name: Java CI with Gradle

on:
  push:
    branches: [ main ]   # Run tests when pushing to the main branch
  pull_request:
    branches: [ main ]   # Run tests when creating a pull request to main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for testing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Upload test reports
      if: always()  # Upload reports even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: build/reports/tests/test
